### ISSUE TITLE
Roadmap to the first release

### ISSUE THREAD

**Issue by futuro** [abiocljs/abio#1]
Hey @mfikes,

As I've been working on asynchronous IO over at https://github.com/futuro/abio/tree/async-io I've
been starting to think about this from a higher level, and I'm interested in your thoughts on what a
v1 might look like for abio.

I've put the list in rough order of importance to immediate usability, and it ignores shell
abstraction for the moment, focusing specifically on `abio.io`.

## Reading/Writing Data
- [x] Reading from a file
  - [x] Synchronous
    - [x] Buffered
    - [x] Unbuffered
  - [x] Asynchronous
    - [x] Buffered
    - [x] Unbuffered
- [x] Writing to a file
  - [x] Synchronous
    - [x] Buffered
    - [ ] Unbuffered
  - [x] Asynchronous
    - [x] Buffered
    - [ ] Unbuffered
- [ ] Streaming
  - [ ] Input streams
    - [ ] Synchronous
      - [ ] Buffered
      - [ ] Unbuffered
    - [ ] Asynchronous
      - [ ] Buffered
      - [ ] Unbuffered
  - [ ] Output Streams
    - [ ] Synchronous
      - [ ] Buffered
      - [ ] Unbuffered
    - [ ] Asynchronous
      - [ ] Buffered
      - [ ] Unbuffered
  - [ ] Duplex Streams
    - [ ] Reading
      - [ ] Synchronous
        - [ ] Buffered
        - [ ] Unbuffered
      - [ ] Asynchronous
        - [ ] Buffered
        - [ ] Unbuffered
    - [ ] Writing
      - [ ] Synchronous
        - [ ] Buffered
        - [ ] Unbuffered
      - [ ] Asynchronous
        - [ ] Buffered
        - [ ] Unbuffered

## Pushing files around
 - [ ] Rename
 - [ ] Move
 - [ ] Copy
 - [ ] Delete

## Making files
 - [ ] Make a directory
 - [ ] Make a link
 - [ ] Make a temp directory
 
## General
 - [ ] `stat`ing a file
 - [ ] List files in a directory

## Altering metadata
 - [ ] Change owner
 - [ ] Change group
 - [ ] Change mode/perms
 - [ ] Change timestamps
 
I originally started work on this in tandem with a fork of abio-node, but I wanted to sanity check
things before I went too far down the rabbit hole in implementation.

Does this look pretty sane?

EDIT: Fixed list format

**Comment by futuro** [comment]
One sec, that list didn't paste right.

**Comment by mfikes** [comment]
The list looks fine to me. One way of looking at things is to simply try to mirror the functionality that exists in Clojure, especially the `clojure.java.io` facilities, which provides a first cut at answering the question "what is the API?" (It answers it in that it is simply an exercise in imitation, inventing no new API.)

On the other hand, though, there is a need to imitate lower level "hosty" things, like getting file attributes. And there is a need to invent new API to provide async versions of the sync stuff found in `clojure.java.io`. I see no way around this but to simply try inventing some API, see if it works, _etc._, and to try to keep the surface area small so that there is very little to consider by libraries that may want to adopt and support the `abio` interface.

**Comment by arichiardi** [comment]
Hello folks, I was looking into this after having read @futuro nRepl article (which is great btw).

I was wondering about the status.

On a more technical note I had a look at the async PR and the only question I had is about callback vs channels, with the second forcing core.async over client code. IMHO a callback is still the best way to go about on libraries, it can always be easily converted to channel.

Looking forward to any answer :))

**Comment by futuro** [comment]
Hi @arichiardi,

I'm glad you liked the article and I'm glad to see there's interest in this project :smile:.

As for the status, I have some uncommitted code from October for both the [abio](https://github.com/futuro/abio/tree/async-io) and [abio-node](https://github.com/futuro/abio-node/tree/async-io) forks I have. I'll revisit this code and update this issue with the current status.

W.r.t callbacks vs. channels, I agree that callbacks are the right way forward. All that's left there is to switch the code over to callback style.

Let me know if you have any thoughts on abio, or code you're working on/hoping to work on. I'd love to hear more about your use case.

Best,
Evan

**Comment by arichiardi** [comment]
That's awesome you have some code leftover, I can also pick it up in case.

My use case is simple and aligned with yours: I would like to have a working lumo nRepl server. This is now my target number one after the port of cljs 1.10 in lumo has been completed :)

Orchard is also on its way and it seems a good moment in time for that as well.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by futuro** [comment]
@arichiardi See https://github.com/abiocljs/abio-node/pull/1 and https://github.com/abiocljs/abio/pull/2 for the async work from my forks.

**Comment by arichiardi** [comment]
Ok cool I will have a look, not sure I can make a full review but will try my best to help.

**Comment by futuro** [comment]
Any amount of review is good, and even better when done by someone who’s interested in using the code :)

**Comment by arichiardi** [comment]
I will hijack this issue to also ask a question about scope: I see these protocols there and I wonder whether it would make sense to have a `abio-aws` or a `abio-azure` against them.

To me it would be kind of useful as the file abstraction is easily extensible to the cloud.

**Comment by futuro** [comment]
I think this is a fine idea. Since abio is aiming to abstract over various platforms, it makes sense to create a handful of implementations so we can iterate on and improve the abstractions before the first release. 

I’d love to hear your feedback on the base abstractions as you make an AWS version.
